--dimProgressToMathSciences
CREATE VIEW dimProgressToMathSciences AS 
SELECT 
       [Region]
      ,[Local_Authority]
      ,[Ref] AS URN
--      ,[School_name]
--      ,[School_type]
--      ,[Gender_info]
      ,[All_A_levels_students]
      ,[A_level_maths_percent_all]
      ,[A_level_further_maths_percent_all]
      ,[A_level_biological_sciences_percent_all]
      ,[A_level_chemistry_percent_all]
      ,[A_level_physics_percent_all]
      ,[A_level_computer_sciences_percent_all]
      ,[Female_A_levels_students]
      ,[A_level_maths_percent_female]
      ,[A_level_further_maths_percent_female]
      ,[A_level_biological_sciences_percent_female]
      ,[A_level_chemistry_percent_female]
      ,[A_level_physics_percent_female]
      ,[A_level_computer_sciences_percent_female]
      ,[Male_A_levels_students]
      ,[A_level_Maths_percent_male]
      ,[A_level_further_maths_percent_male]
      ,[A_level_biological_sciences_percent_male]
      ,[A_level_chemistry_percent_male]
      ,[A_level_physics_percent_male]
      ,[A_level_computer_sciences_percent_male]
  FROM [a_levels_study_db].[dbo].[16-18_Maths_&_Science_A2023]